import "./shim/string_includes";
import "./shim/array_from";
import "./shim/array_isarray";
import "./shim/array_filter";
import "./shim/array_map";
import "./shim/raf";
import { PluginManager } from './dist/PluginManager';
import FunctionManager from './dist/FunctionManager';
import DiffManager from './dist/DiffManager';
import { CompositeManager, LogicManager, CallManager } from './dist/Managers2Fn';
import TweenManager from './dist/TweenManager';
import DOMManager from './dist/DOMManager';
import domClass from './dist/domClass';
import XHR from './dist/xhr';
import hashURL from './dist/hash';
import { createElement, makeNode } from './dist/makeNode';
import URLComponent from './dist/urlc';
import tezClass from './dist/tezClass';
import Data from './dist/data';
import Wrapper from './dist/helper';

export { Data, createElement, PluginManager, FunctionManager, DiffManager, CompositeManager, LogicManager, CallManager, TweenManager, DOMManager, domClass, XHR, hashURL, URLComponent, tezClass };
